add showing all books
TarasHryts/librery_spring pull request #3
Opened 2019-10-22 08:00 UTC by TarasHryts

2019-10-22 09:22 UTC, boroda4436 requested changes

2019-10-22 09:22 UTC, boroda4436 commented on src/main/java/mate/academy/spring/controller/BookController.java
> +import org.dom4j.rule.Mode;
@TarasHryts А де ти це використовуєш?

2019-10-22 09:22 UTC, boroda4436 commented on src/main/java/mate/academy/spring/controller/IndexController.java
> +public class IndexController {
або імплементуй, або видали

2019-10-24 21:27 UTC, boroda4436 requested changes

2019-10-24 21:27 UTC, boroda4436 commented on src/main/java/mate/academy/spring/dao/imp/BookDaoImp.java
> +        TypedQuery<Book> query = sessionFactory
@TarasHryts А чому не через сесію і метод get?

2019-10-24 21:27 UTC, boroda4436 commented on src/main/java/mate/academy/spring/dao/imp/RentDaoImp.java
> +        Rent rent = query.getResultList().stream().findFirst().get();
Щось ти тут намутив. Можеш взагалі спробувати апдейт зробити прямо в БД просто модифікувавши свій перший запит. Зробити не select a update

2019-10-24 21:27 UTC, boroda4436 commented on src/main/java/mate/academy/spring/dao/imp/UserDaoImp.java
> +        TypedQuery<User> query = sessionFactory
@TarasHryts може через стандартний метод сесії?

2019-10-24 22:10 UTC, TarasHryts commented on src/main/java/mate/academy/spring/dao/imp/RentDaoImp.java
> +        Rent rent = query.getResultList().stream().findFirst().get();
не намутив а навпаки зробив коректно. тепер якщо користувач візьме не одну книжку, а кілька штук. наприклад 3 і захоче повернути 2 а одну собі залишити він зможе це зробити

2019-10-24 22:32 UTC, TarasHryts commented on src/main/java/mate/academy/spring/dao/imp/UserDaoImp.java
> +        TypedQuery<User> query = sessionFactory
done

2019-10-24 22:32 UTC, TarasHryts commented on src/main/java/mate/academy/spring/dao/imp/BookDaoImp.java
> +        TypedQuery<Book> query = sessionFactory
done

2019-10-25 10:43 UTC, boroda4436 commented on src/main/java/mate/academy/spring/dao/imp/RentDaoImp.java
> +        Rent rent = query.getResultList().stream().findFirst().get();
Все, зрозумів

2019-10-25 10:43 UTC, boroda4436 approved these changes

2019-10-27 09:49 UTC, merged